unstable_features = true
struct_field_align_threshold = 30
condense_wildcard_suffixes = true
#edition = 2021
enum_discrim_align_threshold = 30
max_width = 132
fn_args_layout = "Compressed"
fn_single_line = true
format_macro_matchers = true
ignore = [ ]
imports_granularity = "Crate"
normalize_comments = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
reorder_modules = true
report_fixme = "Always"
report_todo = "Always"
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true


