apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  labels: 
    app: web-app
  namespace: pantelimon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - image: web-app:2
          name: web-app
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: web-config



