apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: pantelimon
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
    - name: http
      protocol: TCP
      # probably not used here because of NodePort service type
      port: 8080
      # port of the pod
      targetPort: 8081
      # This is the one visible from outside, you use it in curl
      nodePort: 30007



